apps/search/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from apps.search import views


app_name = "search"


urlpatterns = [
    path('', views.search, name="search")
]

project/urls.py
# DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from apps.core.views import robots
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# handler404 = 'apps.core.views.handler404'
# handler500 = 'apps.core.views.handler500'


urlpatterns = [
    path('admin',     admin.site.urls),
 	path('',          include('apps.shop.urls',     namespace='shop')),
    path('',          include('apps.core.urls',     namespace='core')),
    path('',          include('apps.user.urls',     namespace='user')),
    path('cart/',     include('apps.cart.urls',     namespace='cart')),
    path('order/',    include('apps.order.urls',    namespace='order')),
    path('search/',   include('apps.search.urls',   namespace='search')),
    path('commetns/', include('apps.comments.urls', namespace='comments')),
   
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='application/xml'), name='sitemap'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/search/models.py
from django.db import models

# Create your models here.

apps/search/views.py
from django.shortcuts import render
from apps.shop.models import Product
from apps.shop.serializers import ProductSerializer
from Levenshtein import StringMatcher as sm
from django.http import JsonResponse
from fuzzywuzzy import fuzz
from operator import itemgetter
import json, math



# Create your views here.
def search(request):
    args = {
        'param' : request.GET.get('param')
    }


    return render(request, 'search/search__results.html', args)



def search(request):
    context = {}
    on_page = 12
  
    def MatchProdutcs(search_input):
        products = []
        
        def match(inp,val):
            wmtch = 0
            inps = inp.split(' ')
            vals = val.split(' ')
            for iw in inps:
                for vw in vals:
                    ratio = max([fuzz.ratio(iw,vw), fuzz.ratio(iw,vw[:len(iw)+1])])
                    if ratio > 45:
                        wmtch += ratio
                        break
            return wmtch

        if search_input:
            for product in list(Product.objects.all()):
                ratio = match(search_input.lower(), product.name.lower())
                if ratio >= 65:
                    prod = ProductSerializer(product).data
                    prod['ratio'] = ratio
                    products.append(prod) 
            products = sorted(products, key=itemgetter('ratio'), reverse=True)
        
        context['products'] = json.loads(json.dumps(products))
        context['search_input'] = search_input if search_input else ''
        context['products_len'] = len(products)
        context['pages'] = math.ceil(context['products_len'] / 12)
    
        request.session['search_context'] = context.copy()
        return context

    search_input = request.GET.get('param')
    context['param'] = search_input
    context = MatchProdutcs(search_input)
    context['products'] = context['products'][:on_page]
    return render(request, 'search/search__results.html', context)

templates/search/search__results.html
{% extends 'base.html' %}
{% load static %}
<!-- Title -->
{% block title %}Поиск {{ search_query }}{% endblock %}
<!-- Description -->
{% block description %}{% endblock %}
{% block links %}
    <link rel="stylesheet" href="{% static 'css/search/search.css' %}">
    <link rel="stylesheet" href="{% static 'css/shop/catalogue.css' %}">
{% endblock %}


{% block content %}
<div class="search_page">
    <div class="content">
        <h1 class="h2 semibold">Поиск по каталогу</h1>
        <form class="search" action="{% url 'search:search' %}" method="GET">
            
            <input type="search" name="param" placeholder="Найти товар" value="{% if param %}{{ param }}{% endif %}">
            <button type="submit">
                <img src="{% static 'img/ico/search.png' %}" alt="">
                <p>Поиск</p>
            </button>
        </form>
        <ul class="catalogue__list">
            {% for product in products %}
                {% include 'shop/catalogue/catalogue__product.html' %}
            {% endfor %}
        </ul>
    </div>
</div>

{% endblock %}


{% block js %}
{% endblock %}