apps/cart/urls.py
from django.urls import include, path, re_path
from apps.cart import views


app_name = 'order'


urlpatterns = [
    path('add', views.CartView.as_view({'post' : 'add'}), name="add"),
    path('clear', views.CartView.as_view({'get' : 'clear'}), name="clear"),
    path('update', views.CartView.as_view({'post' : 'update'}), name="update"),
    path('remove/<int:number>', views.CartView.as_view({'get' : 'remove'}), name="remove"),
  
]

apps/shop/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from apps.shop import views


app_name = 'shop'

pages = [
    path('about',        TemplateView.as_view(template_name='shop/shop__about.html'),         name='about'),
    path('delivery',     TemplateView.as_view(template_name='shop/shop__delivery.html'),      name='delivery'),
    path('contacts',     TemplateView.as_view(template_name='shop/shop__contacts.html'),      name='contacts'),
    path('guarantee',    TemplateView.as_view(template_name='shop/shop__guarantee.html'),     name='guarantee'),
    path('public_offer', TemplateView.as_view(template_name='shop/shop__publicofer.html'),    name="public_offer"),
    path('politics',     TemplateView.as_view(template_name="shop/product_lp/politics.html"), name="politics"),
]


urlpatterns = [
    path('', views.home, name='home'),
    re_path(
        r'''^catalogue/(?P<category>[-\w/]*)/'''
        r'''product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)'''
        r'''(?:-(?P<variant_id>[0-9]+))?/'''
        r'''?(?:\/(?P<page>characteristics|comments|questions|review|photo|))?/?$''',
        views.ProductPage.as_view({'get':'page'}), 
        name="product"
    ),
    # re_path(
    #     r'''^product
    #     r'''(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)'''
    #     r'''(?:-(?P<variant_id>[0-9]+))?/'''
    #     r'''?(?:\/(?P<page>characteristics|comments|questions|review|photo|))?/?$''',
    #     views.ProductPage.as_view({'get':'page'}), 
    #     name="product"
    # ),
    re_path(
        r'''^catalogue/(?P<category>[-\w/]*)/'''
        r'''product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)/'''
        r'''(?:-(?P<variant_id>[0-9]+))?/'''
        r'''comments/form/$''',
        views.ProductPage.as_view({'get':'comment_form', 'post':'comment_form'}), 
        name="comment_form"
    ),
    re_path(
        r'''^catalogue/(?P<category>[-\w/]*)/'''
        r'''product-(?P<slug>[\w-]+)-id-(?P<product_id>[0-9]+)/'''
        r'''(?:-(?P<variant_id>[0-9]+))?/'''
        r'''question/form/$''',
        views.ProductPage.as_view({'get':'question_form', 'post':'question_form'}), 
        name="question_form"
    ),

    

    re_path('catalogue/(?P<category>[-\w/]*)/$', views.catalogue, name="catalogue"),
    re_path('catalogue/', views.catalogue, name="catalogue"),
    path('watchlist', views.watchlist, name="watchlist"),
    path('set_watchlist/<int:product_id>/<int:variant_id>/', views.set_watchlist, name="set_watchlist"),
    path('set_watchlist/<int:product_id>/', views.set_watchlist, name="set_watchlist"),
    path('facebook_feed', views.facebook_feed, name="facebook_feed"),
    path('', include(pages)),
]

project/urls.py
# DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from apps.core.views import robots
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# handler404 = 'apps.core.views.handler404'
# handler500 = 'apps.core.views.handler500'


urlpatterns = [
    path('admin',     admin.site.urls),
 	path('',          include('apps.shop.urls',     namespace='shop')),
    path('',          include('apps.core.urls',     namespace='core')),
    path('',          include('apps.user.urls',     namespace='user')),
    path('cart/',     include('apps.cart.urls',     namespace='cart')),
    path('order/',    include('apps.order.urls',    namespace='order')),
    path('search/',   include('apps.search.urls',   namespace='search')),
    path('commetns/', include('apps.comments.urls', namespace='comments')),
   
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='application/xml'), name='sitemap'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/shop/models/models__category.py
from django.db import models
from django.urls import reverse
from apps.core.models import Image, NameSlug, Translation, Seo
from mptt.models import MPTTModel, TreeForeignKey


# CATEGORIES
class Category(Translation, NameSlug, Image, Seo, MPTTModel):
    parent =     TreeForeignKey('self', on_delete=models.CASCADE, blank=True, null=True, verbose_name="Родительская категория", related_name='children')
    taxonomy =   models.ForeignKey('shop.GoogleTaxonomy', on_delete=models.CASCADE, blank=True, null=True, help_text='Категория Google')
    num =        models.PositiveIntegerField(default=0, blank=True, verbose_name='Нумерация: Каталог')

    class MPTTMeta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        order_insertion_by = ['name']

    def save(self):
        super(Category, self).save()

    def __str__(self):
        return ' > '.join(self.tree_name)

    def get_absolute_url(self):
        return reverse('shop:catalogue', kwargs={ 'category' : '/'.join(self.tree_slug)})

    @property
    def tree_slug(self):
        return [category.slug for category in self.get_ancestors(include_self=True)]

    @property
    def tree_name(self):
        return [category.name for category in self.get_ancestors(include_self=True)]




 






   




apps/shop/models/models__product__brand.py
from django.db import models
from apps.core.models import NameSlug
from ckeditor.fields import RichTextField
from django.utils.timezone import now
from django.utils.translation import get_language as lang


# BRAND
class Brand(NameSlug):
    class Meta:
        ordering = ('name',)
        verbose_name = 'Бренд'
        verbose_name_plural = 'Бренды'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return '/catalogue/' + self.slug

apps/shop/models/models__product__equipment.py
from django.db import models
from apps.core.models import Translation, Images


# PRODUCTS EQUIPMENT
class ProductEquipmentGroup(Translation, Images):
    parent = models.OneToOneField('shop.Product', on_delete=models.CASCADE, related_name='equipment')
    name = models.CharField(max_length=255, blank=True, null=True)
    text = models.TextField(blank=True, null=True, default='',verbose_name='Текст')

    def __str__(self): return f'Преимущества {str(len(self.items.all()))}'

    class Meta:
        verbose_name = "Комплектация (группа)"
        verbose_name_plural = "Комплектация (группа)"


class ProductEquipment(models.Model):
    parent = models.ForeignKey('shop.ProductEquipmentGroup', on_delete=models.CASCADE, related_name='items')
    num = models.PositiveIntegerField(blank=True, default=None, null=True)
    name = models.CharField(max_length=255, blank=False)
    x = models.PositiveIntegerField(default=0)
    y = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ('num','name',)
        verbose_name = "Комплектация"
        verbose_name_plural = "Комплектации"

apps/shop/views/filter.py
# FILTER PRODUCTS
attrs = {'product' : ['brand'], 'variant' : ['color', 'sizes'],}
QueryParams = Q()
for key, value in attrs.items():
    add = ''
    if key == 'product':
        add = 'parent__'
    for attr in value:
        params = kwargs[attr]
        if params != None:
            params = params.split(',')
            QueryParams &= Q(**{add + attr + '__slug__in':params})

self.context['variants'] = self.context['variants'].filter(QueryParams)
self.context['products'] = self.context['products'].filter(variant__in=self.context['variants']).distinct()
filters = self.selected_product_filters(kwargs['filters'])

filterGroups = ['brand','color','sizes']

def FilterQuery(excluded):
    QueryParams = {}
    curGroup = []
    for group in filterGroups:
        if group in filterGroups and group in self.context.keys() and group != excluded: 
            curGroup.append(group)
    for group in curGroup:
        params = self.kwargs[group]
        try:
            Variant._meta.get_field(group)
            parent = ''
        except:
            parent = 'parent__'
        if params != None:
            QueryParams = {parent + group + '__slug__in' : params.split(',')}
    

    for item in self.context[excluded]:
        ItemQueryParams = copy.deepcopy(QueryParams)   
        ItemQueryParams['pk__in'] = item.json_variant_pks
        variants = self.category_variants.filter(**ItemQueryParams)
        item.len = len(variants)
        params = self.kwargs[excluded]
        if params != None:
            if item.slug in params:
                item.checked = True
    return curGroup

for group in filterGroups:
    FilterQuery(group)

apps/shop/views/views__cart.py
from apps.shop.models import Variant
from django.views.decorators.csrf import csrf_exempt
from django.template.loader import render_to_string
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
import json


def ReturnCartData(request, url=None):
    # variant = Variant.objects.get(pk=int(data['variant_id']))
    cart = Cart(request)

    cart.total = cart.total()
    list_html =  render_to_string('shop/cart/cart__list.html', {'cart':cart})
    total_html = render_to_string('shop/cart/cart__total.html', {'cart':cart})
    order_list_html =  render_to_string('orders/order__productlist.html', {'cart':cart})
    response = {
        'url'   : 'cart',
        'list_html' : list_html,
        'order_list_html' : order_list_html,
        'total_html' : total_html,
        'total' : cart.total
    }
    response = json.dumps(response, ensure_ascii=False).encode('utf8')
    response = json.loads(response.decode('utf8'))
    return JsonResponse(response, safe=False)


@csrf_exempt
def CartAddUpdate(request, update=False):
    if request.method == 'POST':
        cart = Cart(request)
        data = json.loads(request.body.decode())
        if data['update'] == 'true':
            update = True
        cart.add(data, update)
        return ReturnCartData(request)
    else:
        return HttpResponse(status=500)


@csrf_exempt
def CartDelete(request):
    if request.method == 'POST':
        data = json.loads(request.body.decode())
        cart = Cart(request)
        cart.remove(data['variant_id'])
        return ReturnCartData(request)
    else:
        return HttpResponse(status=500)
        

@csrf_exempt
def CartClear(request):
    cart = Cart(request)
    cart.clear()
    return HttpResponse(status=200)
    if request.method == 'POST':
        return HttpResponse(status=200)
    else:
        referer = request.META.get('HTTP_REFERER')
        if referer is not None:
            return redirect(request.META.get('HTTP_REFERER'))
        else:
            return redirect('/')




apps/shop/views/views__catalogue.py
from apps.shop.models import Product, Variant, Category
from django.shortcuts import render, redirect
from django.urls import reverse
from apps.shop.serializers import ProductSerializer
from django.views.decorators.cache import cache_page



def catalogue(request, category=None):
    if category:
        category_param = category.split('/')
        category = Category.objects.get(slug=category_param[-1])
        categories = category.get_descendants(include_self=True)
        products = Product.objects.filter(category__in=categories)
    else:
        products = Product.objects.all()
        
    products = products.filter(in_stock=True)
    serializer = ProductSerializer(products, many=True)
    context = {
        'category' : category,
        'products' : serializer.data,
    }
    return render(request, 'shop/catalogue/catalogue.html', context)


def facebook_feed(request):
    products = Product.objects.filter(in_stock=True)
    return render(request, 'shop/xml/facebook.xml', {'products' : products}, content_type="application/xhtml+xml")

apps/shop/views/views__home.py
from django.shortcuts import render
from apps.shop.models import Product
from apps.shop.serializers import ProductSerializer
from apps.core.models import HomeSlider1, HomeSlider2, HomeSlider3


def home(request):
    products = Product.objects.filter(in_stock=True)
    args = {
        'products_popular' : ProductSerializer(products.order_by('view')[:24], many=True).data,
        'products_newest' :  ProductSerializer(products.order_by('-date')[:24], many=True).data,
        'home_slider_1' : HomeSlider1.objects.all(),
        'home_slider_2' : HomeSlider2.objects.all(),
        'home_slider_3' : HomeSlider3.objects.all(),
    }
    return render(request, 'shop/home/home.html', args)

apps/shop/views/views__search.py
from django.views.decorators.http import require_http_methods
from django.template.loader import render_to_string
from django.http import JsonResponse
from apps.shop.models import Brand, Category, Variant
from fuzzywuzzy import fuzz
from fuzzywuzzy import process
import json
from django.views.decorators.csrf import csrf_exempt
import re



@csrf_exempt
@require_http_methods(["POST"])
def search(request):
    args = {}
    data = json.loads(request.body.decode())['search']
    products = {}
    product_name = []
    brands = []
    categories = []
    product_name = {}
    product_name_human = {}
    color = {}
    if len(data) > 0:
        for item in Variant.objects.all():
            name_parts = [part for part in [item.parent.brand.name, item.parent.name, item.color.name] if part != None]
            name = ' '.join(name_parts)
            
            # product_name.append(name)
            brand_word = ''
            color_word = ''
            category_word = ''
            for word in data.split(' '):
                # CATEGORY
                category_ratio = fuzz.token_sort_ratio(item.parent.category.name, word)
                if category_ratio > 70:
                    categories.append(item.parent.category.slug)
                    category_word = word
                    if item.pk not in products.keys():
                        products[item.pk] = {}
                        products[item.pk]['category_ratio'] = category_ratio
                # BRAND
                brand_ratio = fuzz.token_sort_ratio(item.parent.brand.name, word)
                if brand_ratio > 75:
                    brands.append(item.parent.brand.slug)
                    brand_word = word
                    if item.pk not in products.keys():
                        products[item.pk] = {}
                        products[item.pk]['brand_ratio'] = brand_ratio
                # COLOR
                if item.color != None:
                    color_ratio = fuzz.token_sort_ratio(item.color, word)
                    if color_ratio > 75:

                        color_word = word
                        if item.pk not in products.keys():
                            products[item.pk] = {}
                        products[item.pk]['color_ratio'] = color_ratio
                    # FULL MATCH
            if data in name:
                if item.pk not in products.keys():
                    products[item.pk] = {}
                products[item.pk]['full_match'] = 10000
            # NAME
            name = item.parent.name
            name_ratio = fuzz.token_sort_ratio(item.parent.name, data.replace(brand_word,''))
            if name_ratio > 75:
                if item.pk not in products.keys():
                    products[item.pk] = {}
                products[item.pk]['name_ratio'] = name_ratio
            if item.pk in products.keys():
                products[item.pk]['total'] = 0
                products[item.pk]['pk'] = item.pk

        # SET TOTAL RATIO
        for pk in products.keys():
            for ratio in products[pk]:
                if ratio != 'total':
                    products[pk]['total'] += products[pk][ratio]
            length = len(products[pk].keys()) - 1
            products[pk]['total'] = products[pk]['total'] / length
    

        # SORT BY TOTAL RATIO
        arr = list(products.values())
        n = len(arr)
        for i in range(n):
            for j in range(0, n-i-1):
                if arr[j]['total'] < arr[j+1]['total']:
                    arr[j], arr[j+1] = arr[j+1], arr[j]

        args['products'] = []
        for product in arr:
            args['products'].append(Variant.objects.get(pk=product['pk']))

        args['brands'] = Brand.objects.filter(slug__in=brands)
        args['categories'] = Category.objects.filter(slug__in=categories)
    result = render_to_string('base/header/header__search__output.html', args)
    

    response = {'serarch' : result}
    return JsonResponse(response)

templates/shop/product/product.html
{% extends 'base.html' %}
{% load static %}
<!-- Title -->
{% block title %}{{ product.name }}{% endblock %}
<!-- Description -->
{% block description %}{{ product.translation.short_description }}{% endblock %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product__galery.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product__actions.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product__attr__extra_galery.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/photoswipe/photoswipe.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/photoswipe/default-skin/default-skin.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'lib/plyr/plyr.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/comments/comments.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/comments/comment__form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/comments/product__comments.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/lp/attrs.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product-navigation.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/shop/product__addpage.css' %}">
    {% block links_extended %}{% endblock %}
{% endblock %}

{% block pixel %}
    fbq('track', 'ViewContent', { 
        content_type: 'product',
        content_ids: '{% if variant %}{{ product.pk }}_{{ variant.pk }}{% else %}{{ product.pk }}{% endif %}',
        content_name: '{{ product.name|capfirst }}',
        content_category: '{{ product.category.name }}',
        value: {{ product.price }},
        currency: 'UAH',
    });
{% endblock %}


{% block content %}



<div class="breadcrumbs content">
    <a href="/"><img src="{% static 'img/ico/home.png' %}" alt=""></a>
    <span>></span>
    <a href="{% url 'shop:catalogue' %}">Каталог</a>
    <span>></span>
    {% for node in product.category.get_ancestors %}
        {% if node.image %}
            <img src="{{ node.image_thmb.xs.path }}" alt="">
        {% endif %}
        <a href="{{ node.get_absolute_url }}">{{ node.name }}</a>
        <span>></span>
    {% endfor %}
    {% if product.category.image %}
        <img src="{{ product.category.image_thmb.xs.path }}" alt="">
    {% endif %}
    <a href="{{ product.category.get_absolute_url }}">{{ product.category.name }}</a>
    <span>></span>
    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
</div>

<div class="product product-page">
    <div class="content">
        <a href="{% url 'shop:product' product.category_tree_slug product.slug product.pk  %}">
            <h1 class="h2 product_name">
                {{ product.name }}
                {% if variant %}
                    {% if variant.name %}&nbsp;{{ variant.name }}{% endif %}
                    {% if variant.color.name %}&nbsp;{{ variant.color.name }}{% endif %}
                {% endif %}
            </h1>
        </a>
    </div>
    <div class="product-nav__wrapper">
        <div class="product-nav">
            <ul class="content">
                <a 
                    {% url 'shop:product' product.category_tree_slug product.slug product.pk as the_url %}
                    {% if request.path == the_url %}class="active"{% endif %}
                    href="{% url 'shop:product' product.category_tree_slug product.slug product.pk  %}" 
                    data-api="{% url 'shop:product' 'api' product.slug product.pk  %}"
                ><li>Все о товаре</li></a>
                <a 
                    {% url 'shop:product' product.category_tree_slug product.slug product.pk 'characteristics' as the_url %}
                    {% if request.path == the_url %}class="active"{% endif %}
                    href="{% url 'shop:product' product.category_tree_slug product.slug product.pk 'characteristics' %}"
                    data-api="{% url 'shop:product' 'api' product.slug product.pk 'characteristics' %}"
                ><li>Характеристики</li></a>
                <a 
                    {% url 'shop:product' product.category_tree_slug product.slug product.pk 'comments' as the_url %}
                    {% url 'shop:comment_form' product.slug product.pk as the_url_form %}
                    {% if request.path == the_url or request.path == the_url_form %}class="active"{% endif %}
                    href="{% url 'shop:product' product.category_tree_slug product.slug product.pk 'comments' %}"
                    data-api="{% url 'shop:product' 'api' product.slug product.pk 'comments' %}"
                >
                    <li>Отзывы ({{ product.comments.all|length }})</li>
                </a>
                <a 
                    {% url 'shop:product' product.category_tree_slug product.slug product.pk 'questions' as the_url %}
                    {% if request.path == the_url %}class="active"{% endif %}
                    href="{% url 'shop:product' product.category_tree_slug product.slug product.pk 'questions' %}"
                    data-api="{% url 'shop:product' 'api' product.slug product.pk 'questions' %}"
                ><li>Задать вопрос ({{ product.questions.all|length }})</li></a>
                {% if product.videos.all|length > 0 %}
                    <a 
                        {% url 'shop:product' product.category_tree_slug product.slug product.pk 'review' as the_url %}
                        {% if request.path == the_url %}class="active"{% endif %}
                        href="{% url 'shop:product' product.category_tree_slug product.slug product.pk 'review' %}"
                        data-api="{% url 'shop:product' 'api' product.slug product.pk 'review' %}"
                    ><li>Видеообзор</li></a>
                {% endif %}
                <a 
                    {% url 'shop:product' product.category_tree_slug product.slug product.pk 'photo' as the_url %}
                    {% if request.path == the_url %}class="active"{% endif %}
                    href="{% url 'shop:product' product.category_tree_slug product.slug product.pk 'photo' %}"
                    data-api="{% url 'shop:product' 'api' product.slug product.pk 'photo' %}"
                ><li>Фото</li></a>
            </ul>
        </div>
    </div>

    <div class="product__main content" id="product__main">
        {% block product_data %}{% endblock %}
    </div>
</div>
{% endblock %}

{% block js %}
    <script src="{% static 'lib/plyr/plyr.polyfilled.js' %}"></script>
    <script>
        const setWatchList = "{% if variant.id %}{% url 'shop:set_watchlist' product.id variant.id %}{% else %}{% url 'shop:set_watchlist' product.id %}{% endif %}"
        const player = new Plyr('#player');
    </script>
    <script src="{% static 'lib/sticky-sidebar/sticky-sidebar.min.js' %}"></script>
    <script src="{% static 'lib/photoswipe/photoswipe.js' %}"></script>
    <script src="{% static 'lib/photoswipe/photoswipe-ui-default.js' %}"></script>
    <script src="{% static 'lib/imask/imask.js' %}"></script>
    <script src="{% static 'js/shop/equipment.js' %}"></script>
    <script src="{% static 'js/order/order_form.js' %}"></script>
    <script src="{% static 'js/shop/product__galery.js' %}"></script>
    <!-- <script src="{% static 'js/comments/product__comment.js' %}"></script> -->
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://unpkg.com/tippy.js@6"></script>

    <script>
        tippy('[data-tippy-content]');
        const productMain = document.querySelector('.product__main')
        const productNav = document.querySelector('.product-nav')

        window.addEventListener('scroll', function () {
            windowScrollY = window.scrollY
            if (windowScrollY > productMain.offsetTop - productNav.offsetHeight - 16) {
                productNav.classList.add('fixed')
            } else  {
                productNav.classList.remove('fixed')
            }
        })
    </script>
    <script>
        var element = document.querySelector('input[data-type=phone]');
        var maskOptions = {
            lazy: false,
            mask: '+{38} (000) 000 00 00'
        };
        var mask = IMask(element, maskOptions);
    </script>
    <script>
        var slider = new Swiper ('.form_screen_swiper', {
        // loop: true,
        noSwiping: true,
        spaceBetween: 0,
        navigation: {
        nextEl: '.galery_next',
        prevEl: '.galery_prev',
        },
    })
    </script>
    <script>
        var selectedProdcutColorImage = document.getElementById('selected_prodcut_color_image')
        var productFormSelectColor = document.getElementById('product__form__select__color')
        if (productFormSelectColor != undefined) {
            var productFormSelectColorOptions = productFormSelectColor.querySelectorAll('option')
            productFormSelectColor.onchange = () => {
                for (let option of productFormSelectColorOptions) {
                    if (option.selected) {
                        selectedProdcutColorImage.src = option.dataset.image
                        break
                    }
                }
            }
        } 
    </script>

{% endblock %}

templates/shop/product/product__actions.html
{% load static %}
<div class="product__actions__wrapper" >
    <div class="product__actions">
        <p class="in_stock">Есть в наличии</p>
        {% if product.variant.all|length %}
            <ul class="product__colors">
                {% for item in product.variant.all %}
                    <a href="{{ item.get_absolute_url }}">
                        <li 
                            data-tippy-placement="top"
                            data-tippy-content="{% if item.color %}{{ item.color.name }}{% else %}{{ item.name }}{% endif %}" tabindex="1"
                            class="{% if item == variant %}active{% endif %}"  
                            style="background-image: url({{ item.image_xs }});"
                        ></li>
                    </a>
                {% endfor %}
            </ul>
        {% endif %}
        <form action="{% url 'cart:add' %}" method="POST">
            {% csrf_token %}
            <div class="price">
                {% if product.old_price > product.price %}
                    <div class="discount_wrapper">
                        <p class="old_price">{{ product.old_price }} грн.</p>
                        <p class="discount">-{{ product.get_discount }}%</p>
                    </div>
                {% endif %}
                <p class="current_price">{{ product.price }} грн.</p>
            </div>
            <input type="hidden" name="product_id" value="{{ product.pk }}">
            {% if variant.pk %}
                <input type="hidden" name="variant_id" value="{{ variant.pk }}">
            {% endif %}
            <button type="submit" class="order_button">
                <span>Купить</span>
            </button>
        </form>
    
        <ul class="customer_info">
           <li>
                <p class="title">Оплата и доставка</p>
                <ul>
                    <li>Доставка в любой город Украины с помощью Новой Почты</li>
                    <li>Оплата при получении товара</li>
                </ul>
            </li>
            <li>
                <p class="title">Гарантия</p>
                <ul>
                    <li>6 месяцев</li>
                    <li>Обмен, возврат в течении 14 дней</li>
                </ul>
            </li>
        </ul>
    </div>
</div>



templates/shop/product/product__preferences.html
{% if product.specifications.all %}
    <div class="product__preferences">
        <p class="hd1">Характеристики</p>
        <ul>
            {% for specification in product.specifications.all %}
            <li>
                <p class="key">
                    <!-- <span class="num">{{ forloop.counter }}.</span> -->
                    <span class="name">{{ specification.name }}</span>
                </p>
                <p class="value">{{ specification.text }}</p>
            </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}