apps/cart/urls.py
from django.urls import include, path, re_path
from apps.cart import views


app_name = 'order'


urlpatterns = [
    path('add', views.CartView.as_view({'post' : 'add'}), name="add"),
    path('clear', views.CartView.as_view({'get' : 'clear'}), name="clear"),
    path('update', views.CartView.as_view({'post' : 'update'}), name="update"),
    path('remove/<int:number>', views.CartView.as_view({'get' : 'remove'}), name="remove"),
  
]

apps/order/urls.py
from django.urls import include, path, re_path
from django.views.generic import TemplateView
from apps.order import views


app_name = 'order'


urlpatterns = [
    path('<int:product_id>/<int:variant_id>/',  views.OrderView.as_view(), name='order'),
    path('<int:product_id>/',  views.OrderView.as_view(), name='order'),
    path('',  views.OrderView.as_view(),  name='order'),
    path('success',  TemplateView.as_view(template_name='order/order__success.html'), name='order-success'),
  
]

project/urls.py
# DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from apps.core.views import robots
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# handler404 = 'apps.core.views.handler404'
# handler500 = 'apps.core.views.handler500'


urlpatterns = [
    path('admin',     admin.site.urls),
 	path('',          include('apps.shop.urls',     namespace='shop')),
    path('',          include('apps.core.urls',     namespace='core')),
    path('',          include('apps.user.urls',     namespace='user')),
    path('cart/',     include('apps.cart.urls',     namespace='cart')),
    path('order/',    include('apps.order.urls',    namespace='order')),
    path('search/',   include('apps.search.urls',   namespace='search')),
    path('commetns/', include('apps.comments.urls', namespace='comments')),
   
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='application/xml'), name='sitemap'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/order/models.py
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils import timezone


class Order(models.Model):
    name = models.CharField(blank=False, max_length=500, verbose_name="Имя")
    surname = models.CharField(blank=True, max_length=500, verbose_name="Фамилия")
    patronymic = models.CharField(blank=True, max_length=500, verbose_name="Отчество")
    phone_number = models.CharField(max_length=50, verbose_name="Телефон (только цифры)", editable=False)
    phone = models.CharField(max_length=500, verbose_name="Телефон")
    create = models.DateTimeField(default=timezone.now, verbose_name="Время заказа")
    comment = models.TextField(blank=True)
    # NP
    city = models.CharField(blank=False, max_length=500)
    region = models.CharField(blank=True, max_length=500)
    branch_number = models.CharField(blank=False, max_length=500)

    def __str__(self):
        return ' - '.join([self.create.strftime("%H:%M %d.%m.%Y"), self.city, self.branch_number, self.phone])

    class Meta:
        ordering = ['-create']
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'


class OrderProduct(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='products')
    product = models.ForeignKey('shop.Product', on_delete=models.CASCADE)
    variant = models.ForeignKey('shop.Variant', blank=True, null=True, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    price = models.PositiveIntegerField()
    
    @property
    def total(self):
        return self.quantity * self.price

    class Meta:
        verbose_name = 'Заказ: Товар'
        verbose_name_plural = 'Заказ: Товары'

    def __str__(self):
        return ' - '.join([self.product.name, self.variant.color.name if self.variant else '', str(self.quantity), str(self.price)])

apps/order/views.py
from django.shortcuts import render, redirect
from django.views import View
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.decorators import api_view
from rest_framework.permissions import AllowAny
from apps.order.models import Order, OrderProduct
from apps.shop.models import Product, Variant, Supliers
from apps.shop.functions import serializedExistedProducts
from project import settings
from collections import OrderedDict 
from apps.cart.cart import Cart
import re


class OrderView(View):
    def get(self, request):
        args = {}
        cart = Cart(request)
        if cart.data().get('quantity') == 0:
            try:    return redirect(request.META.get('HTTP_REFERER'))
            except: return redirect('/')
        return render(request, 'order/order.html', args)

    def post(self, request, product_id=None, variant_id=None):
        post = request.POST
        order = Order(
            name = post.get('name'),
            surname = post.get('surname'),
            patronymic = post.get('patronymic') if 'patronymic' in post else '',
            phone_number = int(re.sub("\D", "", post.get('phone'))),
            phone = post.get('phone'),
            city =  post.get('city'),
            branch_number = post.get('branch_number'),
        )
        order.save()
        supliers = {}

        cart = request.session.get(settings.CART_SESSION_ID)
        cart_products = cart['products']
        if len(cart_products) == 0 and product_id is not None:
            cart_products.append({
                'product_id': product_id, 'variant_id' : variant_id, 'quantity' : 1
            })
        
        for item in cart['products']:
            product_id, variant_id  = item['product_id'], item['variant_id']
            product = Product.objects.get(pk=int(product_id))
            if variant_id is not None:
                variant = Variant.objects.get(pk=variant_id)
            else:
                variant = None
            

            if product.suplier is not None:
                if product.suplier not in supliers.keys():
                    supliers[product.suplier] = []
                supliers[product.suplier].append({
                    'product_id' : int(product.suplier_id),
                    'quantity' : int(item['quantity']),
                    'price' : product.price,
                    'color' : variant.color if variant is not None else '-',
                })

            order_product = OrderProduct(
                order=order,
                product=product,
                variant=variant,
                quantity=int(item['quantity']),
                price=product.price
            )
            order_product.save()

        for key, products in supliers.items():
            meth = getattr(Supliers(), key)
            kwargs = {'order' : order, 'products' : products}
            response = meth(**kwargs)
            Order.objects.filter(pk=order.pk).update(comment=str(response))
        del request.session[settings.CART_SESSION_ID]
        return redirect('order:order-success')

templates/order/order.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/order/order.css' %}">
{% endblock %}

{% block pixel %}
   fbq('track', 'AddPaymentInfo')
{% endblock %}


{% block content %}
    <div class="order__page content">
        <div class="order__products__wrapper">
            <p class="h3 semibold pb24">Ваш список покупок</p>
            <div class="order__products">
                <ul class="order__products-list">
                    {% for product in cart.products %}
                        <li class="product">
                            <a href="{{ product.link }}" class="image">
                                <img src="{{ product.image }}" alt="product">
                            </a>
                            <div class="info">
                                <p class="title h4 medium">{{ product.name }}</p>
                                <div class="counter" id="cart-product__counter">
                                    <!-- MINUS -->
                                    <form action="{% url 'cart:update' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="action" value="minus">
                                        <input type="hidden" name="number" value="{{ forloop.counter0 }}">
                                        <input type="hidden" name="path"   value="{{ request.path }}">
                                        <button type="submit" class="action minus">-</button>
                                    </form>
                                    <!-- INPUT -->
                                    <form action="{% url 'cart:update' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="number" value="{{ forloop.counter0 }}">
                                        <input type="hidden" name="path"   value="{{ request.path }}">
                                        <input 
                                            type="number" 
                                            id="product__quantity" 
                                            name="quantity"
                                            data-product_id="{{ product.product_id }}" 
                                            data-variant_id="{{ product.variant_id }}" 
                                            data-cart-update="true" 
                                            value="{{ product.quantity }}" 
                                            min=1 
                                            max=100
                                        >
                                    </form>
                                    <!-- PLUS -->
                                    <form action="{% url 'cart:update' %}" method="POST">
                                        {% csrf_token %}
                                        <input type="hidden" name="action" value="plus">
                                        <input type="hidden" name="number" value="{{ forloop.counter0 }}">
                                        <input type="hidden" name="path"   value="{{ request.path }}">
                                        <button type="submit" class="action minus">+</button>
                                    </form>
                                </div>
                                <!-- TOTAL -->
                                <p class="total">
                                    <span data-price='{{ product.price }}' class="total h5">{{ product.total }}</span>
                                    <span class="pl4 h5">грн.</span>
                                </p>
                                <a href="{% url 'cart:remove' forloop.counter0 %}" class="remove" onclick="CartDelete(this)" data-product_id="{{ product.product_id }}" data-variant_id="{{ product.variant_id }}">
                                    <img class="cart_product_remove" width=8 height=8 src="/static/img/ico/close.png" alt="x">
                                </a>
                            </div>
                        </li>
                    {% endfor %}
                    <p class="order__total-block semibold h4">Всего к оплате: <span id='order_total' class="h3 clr3">{{ cart.total }}</span> <span class="currency h3 clr3"> грн.</span></p>
                </ul>
            </div>
        </div>
       
        <div class="order__form__wrapper ">
            <p class="h3 semibold pb24">Оформление заказа</p>
            <div class="order__form">
                <p class="h5 clr3 semibold pt8 pb24">Введите вашу контактную информацию в форме ниже</p>
                {% include 'order/order__form.html' %}
            </div>
        </div>
        

    </div>

    {% include 'order/tpl/order__products.html' %}
{% endblock %}

{% block js %}
<script src="{% static 'lib/imask/imask.js' %}"></script>
<script>
    var element = document.querySelector('input[data-type=phone]');
    var maskOptions = {
        lazy: false,
        mask: '+{38} (000) 000 00 00'
    };
    var mask = IMask(element, maskOptions);
</script>
<script src="{% static 'js/order/order_form.js' %}"></script>

{% endblock %}

templates/order/order__form.html
{% if varint.pk and product.pk %}
    {% url 'order:order' product.pk varint.pk  as order_url %}
{% elif product.pk %}
    {% url 'order:order' product.pk as order_url %}
{% else %}
    {% url 'order:order' as order_url %}
{% endif %}

<form class="form" action="{{ order_url }}" method="POST" id="order__form" enctype="multipart/form-data" novalidate>
    {% csrf_token %}
    {% if product.variant.all|length > 1 %}
    <p>
        <select name="variant" id="product__form__select__color">
            {% for product_variant in product.variant.all %}
                <option 
                    value="{{ product_variant.pk }}" 
                    data-image="{{ product_variant.images.all.0.image_thmb.s.path }}"
                    {% if variant.pk == product_variant.pk %}selected{% endif %}
                >{% if product_variant.color %}{{ product_variant.color.name }}{% else %}{{ product_variant.name }}{% endif %}
                </option>
            {% endfor %}
        </select>
    </p>
    {% endif %}
    <p>
        <input type="text" 
            placeholder="Имя *" 
            name="name"
            data-name="Имя"
            data-alert="Введите Ваше имя" 
        required>
    </p>
    <p>
        <input type="text" 
            placeholder="Фамилия *" 
            name="surname"
            data-name="Фамилия"
            data-alert="Введите Вашу фамилию" 
        required>
    </p>
   
    <p>
        <input type="text" placeholder="Номер телефона *"
            name="phone"
            data-type="phone" 
            data-alert="Введите номер телефона" 
            data-error="Номер телефона имеет не верный формат"  
        required>
    </p>
    <p>
        <input type="text" placeholder="Город *" 
            name="city"
            data-name="Город"
            data-alert="Введите Ваш город назначения" 
        required>
    </p>
    <p>
        <input type="text" placeholder="Номер отделения Новой Почты *" 
            name="branch_number"
            data-name="Номер отделения Новой Почты"
            data-alert="Введите Ваш город назначения" 
        required>
    </p>
    <button type="submit" class="btn btn-secondary">Оформить заказ</button>
</form>


templates/order/order__success.html
{% extends 'base.html' %}
{% load static %}

{% block pixel %}
   fbq('track', 'Purchase')
{% endblock %}


{% block content %}
<div style="min-height: 40vh;" class="content">
    <h1 class="h1 mt32 mb16">Ваш заказ принят в обработку</h1>
    <p>Очень скоро мы с Вами свяжемся</p>
</div>
{% endblock %}