apps/user/urls.py
from django.urls import path, re_path 
from apps.user import views

app_name = "user"

urlpatterns = [
    path('login',  views.UserViewset.as_view({'get':'login', 'post':'login'}), name="login"),
    path('profile', views.UserViewset.as_view({'get':'profile', 'post':'profile'}), name="profile"),
    path('register', views.UserViewset.as_view({'get':'register', 'post':'register'}), name="register"),
]

project/urls.py
# DJANGO
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf.urls.i18n import i18n_patterns
from django.urls import reverse
from apps.core.views import robots
from django.views.generic import TemplateView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# handler404 = 'apps.core.views.handler404'
# handler500 = 'apps.core.views.handler500'


urlpatterns = [
    path('admin',     admin.site.urls),
 	path('',          include('apps.shop.urls',     namespace='shop')),
    path('',          include('apps.core.urls',     namespace='core')),
    path('',          include('apps.user.urls',     namespace='user')),
    path('cart/',     include('apps.cart.urls',     namespace='cart')),
    path('order/',    include('apps.order.urls',    namespace='order')),
    path('search/',   include('apps.search.urls',   namespace='search')),
    path('commetns/', include('apps.comments.urls', namespace='comments')),
   
    path('ckeditor/', include('ckeditor_uploader.urls')),

    path('robots.txt', TemplateView.as_view(template_name="robots.txt", content_type='text/plain'), name='robots'),
    path('sitemap.xml', TemplateView.as_view(template_name="sitemap.xml", content_type='application/xml'), name='sitemap'),
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += staticfiles_urlpatterns()

apps/user/models.py
# DAJNGO
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from apps.core.functions.functions__validators import checkPhone, checkEmail, check_phone_email, validation_response
import urllib.request
import urllib.parse
import uuid
import copy 


def check_user_exists(email=None, phone=None):
    response = {'status' : True, 'data' : None, 'msg' : [],}
    if email != None:
        if len(CustomUser.objects.filter(email=email)) > 0:
            response['status'] = False
            response['msg'].append('Пользователь с таким Email уже существует.') 
            return response
    elif phone != None:
        if len(CustomUser.objects.filter(phone=phone)) > 0:
            response['status'] = False
            response['msg'].append('Пользователь с таким номером телефона уже существует.')
            return response
    return response





class CustomUserManager(BaseUserManager):
    def create_user(self, username, data={}, password=None, request=None):
        msgs = []
        email, phone = check_phone_email(username)
        # If email or phone exists in valid formsts
        if all(var is None for var in [email, phone]):
            msgs.append('Введите корректный номер Телефона или Email')
            return ' '.join(msgs)
        # If uses exists with this formsts
        user_exists = check_user_exists(email=email, phone=phone)
        # print(user_exists)
        if user_exists['status'] == False:
            msgs += user_exists['msg']
            return ' '.join(msgs)

        if len(msgs) > 0:
            return ' '.join(msgs)
            
        user = self.model(
            username = uuid.uuid4(),
            email = email,
            phone = phone,
            name = data['name'] if 'name' in data.keys() else None,
            surname = data['surname'] if 'surname' in data.keys() else None,
        )

        if password != None:
            user.set_password(password)
        user.save(using=self._db)
        return user

    


    def create_superuser(self, username, password, email=None, phone=None):
        user = self.create_user(
            username=username, password=password,
        )
        if isinstance(user, CustomUser) == False:
            raise ValueError(user)
        user.is_admin = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    username = models.CharField(max_length=255, blank=True, null=True, unique=True)
    email =    models.EmailField(max_length=255, blank=True, null=True, unique=True, verbose_name="E-mail")
    phone =    models.CharField(max_length=15, blank=True, null=True, unique=True, verbose_name="Телефон")
    name =        models.CharField(max_length=255, blank=True, null=True, verbose_name="Имя")
    surname =     models.CharField(max_length=255, blank=True, null=True, verbose_name="Фамилия")
    patronymic =  models.CharField(max_length=255, blank=True, null=True, verbose_name="Отчество")
    is_active =   models.BooleanField(default=True)
    is_admin =    models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        if self.name and self.surname:
            return ' '.join([self.name, self.surname])
        elif self.name: 
            return self.name
        else:
            return self.email

    def has_perm(self, perm, obj=None):
        return True

    def has_module_perms(self, app_label):
        return True

    @property
    def is_staff(self):
        return self.is_admin

    def save(self,*args,**kwargs):
        # self.phone = checkPhone(self.phone)
        super(CustomUser, self).save(*args,**kwargs)

apps/user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.urls import reverse
from apps.user.models import CustomUser
from rest_framework import viewsets
from rest_framework.response import Response
from rest_framework.permissions import AllowAny
from django.core.exceptions import ValidationError
from django.core.validators import validate_email



def email_validator(value):
    try: 
        validate_email(value)
        return  True
    except:  return 'E-mail Имеет не корреетный форма'

validator = {
    'email' : email_validator
}




class UserViewset(viewsets.ViewSet):
    permission_classes = [AllowAny]
    context = {}
    

    def login(self, request):
        args = self.context 
        args['redirect'] = request.GET.get('redirect')

        if request.method == 'POST':
            last_url = request.META.get('HTTP_REFERER')
            data = request.data
            # FIND USER
            try: user = CustomUser.objects.get(email=data.get('email'))
            except: 
                user = None
                args['msg'] = "Пользователь с таким E-mail не зарегестрирован в системе"
            # TRY PASSWORD
            if user:
                user = authenticate(request, username=user.email, password=data['password'])
                if user is not None:
                    login(request, user)
                    if args['redirect']:
                        return redirect(args['redirect'])
                    else:
                        return redirect('/')
                else:
                    args['msg'] = "Введен не правильный пароль"
        return render(request, 'user/login.html', args)

    def register(self, request):
        errors, args = [], {}
        args['redirect'] = request.GET.get('redirect')
        if request.method == 'POST':
            data=request.data
            args['data']=data
             # EMAIL
            email = data.get('email')
            try: validate_email(data.get('email'))
            except: errors.append('E-mail Имеет не корреетный форма')
            # USER
            user = CustomUser.objects.filter(email=email).first()
            if user: errors.append('Пользователь с таким E-mail уже зарегестрирован')
            # PASSWORD
            password, password2 = data.get('password'), data.get('password2')
            if password:
                if len(password) < 6:
                    errors.append('Пароль слишком короткий')
                if password != password2:
                    errors.append('Пароли не совпадают')
            else:
                errors.append('Введите пароль')
            if len(errors) == 0:
                user = CustomUser(
                    email = data.get('email'),
                    name = data.get('name'),
                    surname = data.get('surname'),
                )
                user.set_password(password)
                user.save()
                login(request, user)
                if args['redirect']:
                    return redirect(args['redirect'])
                else:
                    return redirect('/')
            else:
                args['msg'] = ', '.join(errors)

        return render(request, 'user/register.html', args)
        

    def profile(self, request):
        auth = False
        if auth == False:
            return render(request, 'user/login.html')
        else:
            return redirect('/')

templates/user/login.html
{% extends 'base.html' %}
{% load static %}
    
{% block links %}
    <link rel="stylesheet" href="{% static 'css/user/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="content">
    <div class="breadcrumbs">
        <a href="/"><img src="{% static 'img/ico/home.png' %}" alt=""></a>
        <span>></span>
        <a href="{% url 'user:login' %}">Вход</a>
    </div>
</div>
<div class="authentication">
    <!-- LOGIN -->
    <div class="login content">
        <p class="h3 title">Авторизация пользователя</p>
        
        <form class="form" id="form_auth" action="{% url 'user:login' %}{% if redirect %}?redirect={{ redirect }}{% endif %}" method="POST">
            {% csrf_token %}
            <div class="message {% if msg %}active{% endif %}">
                {{ msg }}
            </div>
            <div class="data">
                <label>
                    <input 
                        class="input" 
                        data-type="email" 
                        type="email" 
                        name="email"
                        data-alert="Введите Ваш Email" 
                        data-error="Email имеет не верный формат"
                        placeholder="E-mail"
                        {% if data.email %}
                            value="{{ data.email }}"
                        {% endif %}
                        required>
                </label>
            
                <label>
                    <input 
                        name="password"
                        data-type="password" 
                        type="password" 
                        placeholder="Пароль"
                        required>
                    <div class="show_password"></div>
                </label>
        
                <button type="submit" class="col2 button h4 bold">Войти</button>
                <p class="question mt24 center">Еще нет учетной запси?</p>
                <a href="{% url 'user:register' %}{% if redirect %}?redirect={{ redirect }}{% endif %}" class="button h4 bold">Зарегестрируйтесь</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block js %}
    <!-- <script src="{% static 'lib/form_validation.js' %}"></script> -->
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% load static %}
    
{% block links %}
    <link rel="stylesheet" href="{% static 'css/user/authentication.css' %}">
{% endblock %}

{% block content %}
<div class="content">
    <div class="breadcrumbs">
        <a href="/"><img src="{% static 'img/ico/home.png' %}" alt=""></a>
        <span>></span>
        <a href="{% url 'user:register' %}">Регистрация</a>
    </div>
</div>

<div class="authentication">
    <!--REGISTER -->
    <div class="content">
        <div class="register content_right">
            <p class="h3 title">Регистрация нового пользователя</p>
            <form class="form" id="form_register" action="{% url 'user:register' %}{% if redirect %}?redirect={{ redirect }}{% endif %}"  method="POST">
                {% csrf_token %}
                <div class="message {% if msg %}active{% endif %}">
                    {{ msg }}
                </div>
                <div class="data">
                    <label>
                        <input data-type="email" class="input" type="email" name="email" placeholder="E-mail" data-error="Введите Ващ E-mail" required>
                    </label>
                    <label>
                        <input data-type="text_only" type="text" name="name"  placeholder="Имя" required>
                    </label>
                    <label>
                        <input data-type="text_only" type="text" name="surname"  placeholder="Фамилия" required>
                    </label>
                    <label>
                        <input data-type="password" type="password" name="password"  placeholder="Пароль" id="register_password_input" required>
                        <div class="show_password"></div>
                    </label>
                    <label>
                        <input data-type="password2" type="password" name="password2"  placeholder="Подтверждение пароля" data-parent="parent" required>
                        <div class="show_password"></div>
                    </label>
                    <a href="{% url 'user:login' %}{% if redirect %}?redirect={{ redirect }}{% endif %}" class="question center">Уже зарегестрированы?</a>
                    <button type="submit" class="col2 button h4 bold">Создать аккаунт</button>
                    <p class="center col2">
                        <span>Нажимая на кнопку Создать аккаунт, Вы соглашаетесь с </span>
                        <a class="bold" href="">условиями и положениями</a>
                    </p>
                </div>
            </form>
        </div>
    </div>

</div>
{% endblock %}

{% block js %}
    <script src="{% static 'lib/form_validation.js' %}"></script>
{% endblock %}